package com.lczyfz.edp.springboot.demo.sys.vo.PageVO;

import com.lczyfz.edp.springboot.core.validation.Create;
import com.lczyfz.edp.springboot.core.validation.Update;
import com.lczyfz.edp.springboot.core.vo.PageVO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.commons.CommonsMultipartFile;

import javax.validation.constraints.NotBlank;
import java.util.Date;

@Data
@ApiModel(value = "QuetionPageVO",description = "题目实体vo")
public class QuetionPageVO extends PageVO {

    @ApiModelProperty(value = "id")
    @NotBlank(groups = {Update.class},message = "不能为空")
    private String id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quetion.name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "name",example = "解析几何填空")
    @NotBlank(groups = {Create.class},message = "不能为空")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quetion.type
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "type",example = "math")
    @NotBlank(groups = {Create.class},message = "不能为空")
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quetion.centent
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "content",example = "3x+2y+5=0")
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_quetion.create_by
     *
     * @mbggenerated
     */
    private String createBy;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_quetion.office_id
     *
     * @mbggenerated
     */
    private String officeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_quetion.img
     *
     * @mbg.generated
     */
    private String img;
}
