package com.lczyfz.edp.springboot.demo.sys.vo.PageVO;

import com.baomidou.mybatisplus.annotation.TableField;
import com.lczyfz.edp.springboot.core.validation.Create;
import com.lczyfz.edp.springboot.core.vo.PageVO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.constraints.NotBlank;
import java.util.Date;

@Data
@ApiModel(value = "SubcriberPageVO", description = "用户实体VO")
public class SubcriberPageVO extends PageVO {

    @ApiModelProperty(value = "id")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "name")
    @NotBlank(groups = {Create.class},message = "不能为空")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "password")
    @NotBlank(groups = {Create.class},message = "不能为空")
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.email
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "email",example = "2528236@136.com")
    @NotBlank(groups = {Create.class},message = "不能为空")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.is_teacher
     *
     * @mbggenerated
     */
    @TableField("is_teacher")
    private Byte teacherOrNot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_quetion.office_id
     *
     * @mbggenerated
     */
    private String officeId;

}
