package com.lczyfz.edp.springboot.demo.sys.vo.PageVO;

import com.baomidou.mybatisplus.annotation.TableField;
import com.lczyfz.edp.springboot.core.vo.PageVO;
import io.swagger.annotations.ApiModel;
import lombok.Data;

import java.util.Date;

@Data
@ApiModel(value = "TestRecordPageVO",description = "考试记录实体vo")
public class TestRecordPageVO extends PageVO {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.test_id
     *
     * @mbggenerated
     */
    private String testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.begin_time
     *
     * @mbggenerated
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.submit_time
     *
     * @mbggenerated
     */
    private Date submitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.is_correct
     *
     * @mbggenerated
     */
    private Byte correctOrNot;

    private String officeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_test_record.submiter
     *
     * @mbg.generated
     */
    private String submiter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_test_record.pap_id
     *
     * @mbg.generated
     */
    private String papId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_test_record.correct_paper
     *
     * @mbg.generated
     */
    private String correctPaper;
}
