package com.lczyfz.edp.springboot.demo.sys.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.lczyfz.edp.springboot.core.config.Global;
import com.lczyfz.edp.springboot.core.entity.DataEntity;
import com.lczyfz.edp.springboot.core.utils.SnowFlakeIdUtils;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@TableName("ds_test_record")
public class correctOrNot extends DataEntity<com.lczyfz.edp.springboot.demo.sys.entity.correctOrNot> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.test_id
     *
     * @mbggenerated
     */
    private String testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.begin_time
     *
     * @mbggenerated
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.submit_time
     *
     * @mbggenerated
     */
    private Date submitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.is_correct
     *
     * @mbggenerated
     */
    @TableField("is_correct")
    private Byte correctOrNot;

    private String officeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_test_record.submiter
     *
     * @mbg.generated
     */
    private String submiter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_test_record.pap_id
     *
     * @mbg.generated
     */
    private String papId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_test_record.paper
     *
     * @mbg.generated
     */
    private String paper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_test_record.correct_paper
     *
     * @mbg.generated
     */
    private String correctPaper;


    @Override
    public void preInsert() {
        if (!this.isNewRecord) {
            this.setId(SnowFlakeIdUtils.getIdWorker(Global.WORKER_ID, Global.DATA_CENTER_ID).nextId() + "");
        }

        LocalDateTime localDateTime = LocalDateTime.now();
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH-mm-ss");

        this.updateDate = new Date();
        try {
            this.createDate = new SimpleDateFormat("dd-MM-yyyy HH-mm-ss").parse(localDateTime.format(dateTimeFormatter));
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
    }

}