package com.lczyfz.edp.springboot.demo.sys.entity;

import com.lczyfz.edp.springboot.core.config.Global;
import com.lczyfz.edp.springboot.core.entity.DataEntity;
import com.lczyfz.edp.springboot.core.utils.SnowFlakeIdUtils;
import io.swagger.annotations.ApiModel;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(value = "Quetion", description = "Quetion")
public class Quetion extends DataEntity<Quetion> {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_quetion.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_quetion.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_quetion.centent
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_quetion.test_paper_belong
     *
     * @mbg.generated
     */
    private String testPaperBelong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_quetion.img
     *
     * @mbg.generated
     */
    private String img;

    private String officeId;

    @Override
    public void preInsert() {
        if (!this.isNewRecord) {
            this.setId(SnowFlakeIdUtils.getIdWorker(Global.WORKER_ID, Global.DATA_CENTER_ID).nextId() + "");
        }

        LocalDateTime localDateTime = LocalDateTime.now();
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH-mm-ss");

        this.updateDate = new Date();
        try {
            this.createDate = new SimpleDateFormat("dd-MM-yyyy HH-mm-ss").parse(localDateTime.format(dateTimeFormatter));
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void preUpdate() {
        this.updateDate = new Date();
    }


}