package com.lczyfz.edp.springboot.demo.sys.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.lczyfz.edp.springboot.core.config.Global;
import com.lczyfz.edp.springboot.core.entity.DataEntity;
import com.lczyfz.edp.springboot.core.entity.User;
import com.lczyfz.edp.springboot.core.utils.SnowFlakeIdUtils;
import com.lczyfz.edp.springboot.core.utils.StringUtils;
import com.lczyfz.edp.springboot.core.utils.UserUtils;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@TableName("ds_user")
public class Subcriber extends DataEntity<Subcriber> {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.is_teacher
     *
     * @mbggenerated
     */
    @TableField("isTeacher")
    private Byte teacherOrNot;

    private String officeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.email
     *
     * @mbg.generated
     */
    private String email;

    @Override
    public void preInsert() {
        if (!this.isNewRecord) {
            this.setId(SnowFlakeIdUtils.getIdWorker(Global.WORKER_ID, Global.DATA_CENTER_ID).nextId() + "");
        }

        LocalDateTime localDateTime = LocalDateTime.now();
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH-mm-ss");

        this.updateDate = new Date();
        try {
            this.createDate = new SimpleDateFormat("dd-MM-yyyy HH-mm-ss").parse(localDateTime.format(dateTimeFormatter));
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void preUpdate() {
        this.updateDate = new Date();
    }
}