package com.lczyfz.edp.springboot.demo.sys.vo;

import com.lczyfz.edp.springboot.core.validation.Create;
import com.lczyfz.edp.springboot.core.validation.Update;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiParam;
import lombok.Data;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.commons.CommonsMultipartFile;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;

@Data
@ApiModel(value = "QuestionVO", description = "题目实体VO")
public class QuetionVO {

    @ApiModelProperty(value = "id")
    @NotBlank(groups = {Update.class},message = "不能为空")
    private String id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quetion.name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "name",example = "解析几何填空")
    @NotBlank(groups = {Create.class},message = "不能为空")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quetion.type
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "type",example = "math")
    @NotBlank(groups = {Create.class},message = "不能为空")
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quetion.centent
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "content",example = "3x+2y+5=0")
    @NotBlank(groups = {Create.class},message = "不能为空")
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_quetion.office_id
     *
     * @mbggenerated
     */
    private String officeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_quetion.test_paper_belong
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "testPaperBelong",example = "501429147029991424")
    private String testPaperBelong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_quetion.img
     *
     * @mbg.generated
     */
    private String img;



    public QuetionVO(String name, String type, String centent) {
        this.name = name;
        this.type = type;
        this.content = centent;
    }
}
