package com.lczyfz.edp.springboot.demo.sys.vo;

import com.baomidou.mybatisplus.annotation.TableField;
import com.lczyfz.edp.springboot.core.validation.Create;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.util.Date;


@Data
@NoArgsConstructor
@AllArgsConstructor
@ApiModel(value = "SubcriberVO", description = "用户实体VO")
public class SubcriberVO{

    @ApiModelProperty(value = "id")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "name")
    @NotBlank(groups = {Create.class},message = "不能为空")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "password")
    @NotBlank(groups = {Create.class},message = "不能为空")
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds_user.email
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "email",example = "2528236@136.com")
    @NotBlank(groups = {Create.class},message = "不能为空")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.is_teacher
     *
     * @mbggenerated
     */
    @TableField("is_teacher")
    @ApiModelProperty(value = "teacherOrNot",example = "1")
    @NotNull(groups = {Create.class},message = "不能为空")
    private Byte teacherOrNot;


    public SubcriberVO(String name, String password) {
        this.name = name;
        this.password = password;
    }
}
